server:
  port: 8080

spring:
  datasource:
    # MySQL数据源的配置
    url: jdbc:mysql://localhost:3306/db_online_ssm?characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver